<?php
class ConfigMagik {
    public $PATH = null;
    public $VARS = array();
    public $SYNCHRONIZE = false;
    public $PROCESS_SECTIONS = true;
    public $PROTECTED_MODE = false;
    public $ERRORS = array();

    public function __construct($path = null, $synchronize = false, $process_sections = true) {
        $this->PROCESS_SECTIONS = $process_sections;
        $this->SYNCHRONIZE = $synchronize;

        if ($path !== null) {
            $this->PATH = $path;

            if (!is_file($path)) {
                if (!file_put_contents($path, "")) {
                    $this->ERRORS[] = "Could not create config file at '$path'";
                }
            } else {
                if (!$this->load($path)) {
                    $this->ERRORS[] = "Failed to load config file at '$path'";
                }
            }
        }
    }

    public function get($key, $section = null) {
        if ($this->PROCESS_SECTIONS && $section !== null) {
            return $this->VARS[$section][$key] ?? null;
        } else {
            return $this->VARS[$key] ?? null;
        }
    }

    public function set($key, $value, $section = null) {
        if ($this->PROCESS_SECTIONS) {
            if ($section === null) {
                $this->ERRORS[] = "set() - section is required when PROCESS_SECTIONS is enabled.";
                return false;
            }
            $this->VARS[$section][$key] = $value;
        } else {
            $this->VARS[$key] = $value;
        }

        if ($this->SYNCHRONIZE) {
            return $this->save();
        }

        return true;
    }

    public function removeKey($key, $section = null) {
        if ($this->PROCESS_SECTIONS && $section !== null) {
            if (!isset($this->VARS[$section][$key])) {
                $this->ERRORS[] = "removeKey() - Key '$key' not found in section '$section'.";
                return false;
            }
            unset($this->VARS[$section][$key]);
        } else {
            if (!isset($this->VARS[$key])) {
                $this->ERRORS[] = "removeKey() - Key '$key' not found.";
                return false;
            }
            unset($this->VARS[$key]);
        }

        if ($this->SYNCHRONIZE) {
            return $this->save();
        }

        return true;
    }

    public function removeSection($section) {
        if (!isset($this->VARS[$section])) {
            $this->ERRORS[] = "removeSection() - Section '$section' not found.";
            return false;
        }
        unset($this->VARS[$section]);

        if ($this->SYNCHRONIZE) {
            return $this->save();
        }

        return true;
    }

    public function load($path = null) {
        $target = $path ?? $this->PATH;
        if (!is_file($target)) {
            $this->ERRORS[] = "load() - File '$target' not found.";
            return false;
        }

        $this->VARS = parse_ini_file($target, $this->PROCESS_SECTIONS);
        if ($this->VARS === false) {
            $this->ERRORS[] = "load() - Failed to parse '$target'.";
            return false;
        }

        return true;
    }

    public function save($path = null) {
        $target = $path ?? $this->PATH;
        $content = "";

        if ($this->PROTECTED_MODE) {
            $content .= "<?php\n; /*\n; -- BEGIN PROTECTED_MODE\n";
        }

        $content .= "; This file was generated by ConfigMagik\n";
        $content .= "; Do not edit manually unless you know what you're doing.\n";
        $content .= "; Last modified: " . date('Y-m-d H:i:s') . "\n\n";

        if ($this->PROCESS_SECTIONS) {
            foreach ($this->VARS as $section => $pairs) {
                $content .= "[$section]\n";
                foreach ($pairs as $key => $value) {
                    $content .= "$key = \"" . addslashes($value) . "\"\n";
                }
                $content .= "\n";
            }
        } else {
            foreach ($this->VARS as $key => $value) {
                $content .= "$key = \"" . addslashes($value) . "\"\n";
            }
        }

        if ($this->PROTECTED_MODE) {
            $content .= "; -- END PROTECTED_MODE\n; */\n?>";
        }

        if (file_put_contents($target, $content) === false) {
            $this->ERRORS[] = "save() - Failed to write to '$target'.";
            return false;
        }

        return true;
    }

    public function listKeys($section = null) {
        if ($this->PROCESS_SECTIONS && $section !== null && isset($this->VARS[$section])) {
            return array_keys($this->VARS[$section]);
        }

        return array_keys($this->VARS);
    }

    public function listSections() {
        if (!$this->PROCESS_SECTIONS) {
            return [];
        }

        return array_filter(array_keys($this->VARS), function ($k) {
            return is_array($this->VARS[$k]);
        });
    }

    public function toString($output_type = 'TEXT') {
        $output_type = strtoupper($output_type);
        $out = "";

        if ($output_type === 'TEXT') {
            ob_start();
            print_r($this->VARS);
            $out = ob_get_clean();
        } elseif ($output_type === 'HTML') {
            $out .= "<table border='1' cellpadding='5'>";

            if ($this->PROCESS_SECTIONS) {
                foreach ($this->VARS as $section => $pairs) {
                    $out .= "<tr><th colspan='3'>$section</th></tr>";
                    foreach ($pairs as $key => $value) {
                        $out .= "<tr><td></td><td>$key</td><td>$value</td></tr>";
                    }
                }
            } else {
                foreach ($this->VARS as $key => $value) {
                    $out .= "<tr><td>$key</td><td>$value</td></tr>";
                }
            }

            $out .= "</table>";
        } else {
            $this->ERRORS[] = "toString() - Unknown output type '$output_type'.";
        }

        return $out;
    }
}
?>
