MYSQL_ROOT_USER=root
MYSQL_ROOT_PASS=your_mysql_root_password

NETZ_DB_USER=netz
NETZ_DB_PASS=netz_password
NETZ_DB_NAME=NETz
MYSQL_SERVER=localhost

EMAIL_SERVER=localhost
EMAIL_PORT=25
ADMIN_EMAIL=you@example.com

LOG_DIR=/usr/netz/logs/
UPLOAD_DIR=/usr/netz/uploads/
WEB_USER=www-data

CREATE_LOG_DIR=y
CREATE_UPLOAD_DIR=y
ADD_SUDOERS=y
ADD_CRON=y
