CREATE TABLE `REMINDERS` (
  `USERNAME` varchar(255) NOT NULL DEFAULT '',
  `REMINDER_NAME` varchar(100) default '',
  `REMINDER_DATE_TIME` datetime default NULL,
  `REMINDER_ADVANCE_TIME` varchar(20) default '',
  `DESCRIPTION` longtext,
  KEY `USERNAME` (`USERNAME`),
  KEY `REMINDER_NAME` (`REMINDER_NAME`),
  KEY `REMINDER_DATE_TIME` (`REMINDER_DATE_TIME`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
ALTER TABLE `USERS` ADD `TIME_ZONE_OFFSET` INT NOT NULL DEFAULT '0';
